"""
This script processes "long poems" from the `data/full_length` directory based on predefined splitting instructions.
It copies the resulting chunks and the remaining poems into the `data/chunked` directory. The "long poems" are 
defined in the `long_poems.csv` file, which is generated by the `full_length_poems_stats.py` script. The splitting 
points are chosen to create chunks that are approximately 1000 tokens long on average and no longer than 2048 tokens.
"""

import os
import re
import shutil


SPLITTING_INSTRUCTIONS = """
1869. (I. )/002 - Dvadsiaty rok.txt | 133 | 259
1869. (II.)/061 - Ospievané je už, už všetko.txt | 78
1916 - 1920/001 - V jesennú polnoc.txt | 82 (*) | 189 (*) | 249 (*) | 302 (*)
1916 - 1920/002 - Hymna.txt | 99
Agar/001 - Agar.txt | 137 | 186 (Svit nevídaný sfarbil každé líce) | 327 | 405 | 502 (*) | 603 | 692 | 868 (*) | 982 | 1099 (*) | 1192 | 1292 | 1380 | 1495 | 1588 | 1703 | 1794 | 1866
Azyl/001 - Azyl.txt | 88
Básne príležitostné/002 - Púť živeny.txt | 91 | 196 | 245 | 329 | 360 (- - - - - - - -)
Básne príležitostné/003 - 24. novembra 1910.txt | 69
Básne príležitostné/004 - Michal Miloslav Hodža.txt | 111
Básne príležitostné/005 - Na storočnú pamiatku.txt | 100
Básne príležitostné/009 - Kantáta.txt | 119
Básne príležitostné/010 - Prívet.txt | 62 | 195 | 272 | 383
Básne príležitostné/011 - Pri hrobe Pavla Mudroňa.txt | 65
Básne príležitostné/012 - Nad knihou Vrchlického.txt | 68
Básne príležitostné/013 - Pri hrobe Svetozára Hurbana-Vajanského.txt | 46
Básne príležitostné/014 - Storočná pamiatka narodenia Andreja Radlinského v Dolnom Kubíne.txt | 53
Básne príležitostné/017 - Mládeži československej.txt | 144 (Priznajme však milšie, krotšie)
Básne príležitostné/018 - Národe drahý.txt | 71 (Ak o tom všetkom)
Básne príležitostné/019 - Poslanie verejnosti československej.txt | 91
Básne príležitostné/020 - K znovutovoreniu Matice slovenskej.txt | 107 (Ľudstvo, pravda,) | 189 (A, skladatelia,)
Básne príležitostné/021 - Predslov k otvoreniu Gymnázia v Dolnom Kubíne.txt | 128
Básne príležitostné/026 - Mladé Slovensko.txt | 81
Básne príležitostné/028 - Na pamäť.txt | 99 (Tak, hľa! prikrásil si) | 206
Básnické prviesenky Jozefa Zbranského/003 - Ja som Slovák.txt | 62
Básnické prviesenky Jozefa Zbranského/006 - Na Všechsvätých.txt | 71
Básnické prviesenky Jozefa Zbranského/020 - Kostol.txt | 73 (*)
Básnické prviesenky Jozefa Zbranského/028 - K tej slovenskej mládeži.txt | 69
Básnické prviesenky Jozefa Zbranského/038 - Roztomil.txt | 102 (*) | 190 (*)
Bútora a Čútora/001 - Bútora a Čútora.txt | 78 | 153 | 209 | 259 | 331 | 375 | 482 | 578 (*)
Dozvuky I/008 - Na skalisku stred hlbokých lesov.txt | 83
Dozvuky I/015 - Nové zvuky počujem.txt | 62
Dozvuky I/021 - Maliarka prišla k nám z ďalekých končín.txt | 68 (Zmĺkol som bez slova. Už sa len dívam)
Dozvuky I/032 - Spí matka zem.txt | 75
Dozvuky II/004 - Chyžnianskemu.txt | 83 (Tu umysleli si:) | 154 (Už za slúžku ju aspoň načim vziať:) | 218 (To už dopálilo)
Dozvuky II/010 - Zawilińskému.txt | 66
Dozvuky II/014 - Je Obrátenie Pavla.txt | 95 (A potom čiže nepadajú hviezdy) | 197 (A moja duša priskočila kmotrou) | 306 (Môj obzor) | 386 (Pekne! Nuž a pokrok) 
Dozvuky II/021 - Mňa vzal si národ za predmet.txt | 50
Dozvuky II/024 - Hluk odšumel - v dym blýskavica hravá....txt | 68
Dozvuky II/027 - Nie zvláštnosť? mne svet vyhýba.txt | 105
Dozvuky II/029 - Prejdite trebárs celú prírodu.txt | 106
Dozvuky II/044 - Dve obce schodím zavše prechádzkou.txt | 100 | 179
Dozvuky III/006 - Rád oblaky v ich ceste odprevádzam.txt | 82 | 145
Dozvuky III/007 - O modrom vtáku vám včuľ zaspievam.txt | 145 
Ežo Vlkolinský/001 - Ežo Vlkolinský.txt | 144 (*) | 257 | 402 | 439 (*) | 539 | 659 | 715 (*) | 844 | 988 | 1104 | 1220 | 1342 | 1467 (*) | 1564 (I tančili by boli - ale vtom,) | 1628 (V tých výtržnostiach, hluku, pohyboch) | 1734 (Tak zvlášte ťažkaly si: Ezechiel) | 1789 | 1873 (Odpoveď) | 2009 | 2138 | 2264 (*) | 2340 | 2451 | 2554 | 2715 (A Blažko nadpriadol: "Ten vážny sľub) | 2779 | 2893 (Hej, sestra, obed už raz! -" "Teraz však) | 3037 | 3153 (Práve na drobkoch) | 3264 (Dosť odhŕňal sa, že ver' ďakuje,) | 3350 (V to muzika vše zhrala; ktorý ten) | 3474 | 3587 (A zazdravkali novomanželom) | 3764 | 3886 | 3977 | 4071 (Ferdo: "Aspoň raz) |4163 | 4247 | 4357 (*) | 4516 (*) | 4625
Gábor Vlkolinský/001 - Gábor Vlkolinský.txt | 166 | 262 | 377 | 524 (Vrchnosti našské, riady, svobody) | 610 | 659 (*) | 735 | 844 | 964 | 1116 | 1223 | 1382 | 1427 (*) | 1526 (To bude rozkoš!... Ale drví ťa,) | 1685 (*) | 1796 | 1896 | 2053 | 2201 | 2302 (Konečne, bolo takmer podvečer) | 2414 (A tanec trval. I ver' trval by) | 2476 | 2544 (*) | 2572 | 2614 | 2624 | 2694 | 2762 (Na mise, jestli opekance nie,) | 2869 | 2965 (Troch bratov mala: ovšem, v úradoch) | 3113 | 3237 (*) | 3340 (Tu Tomáš, zazrúc mrzko, na múrik) | 3459 | 3568 (*) | 3677 (I sama pošla za ním, zhanbená -) | 3774 (I Gábor, trebárs zdal sa nevrlým,) | 3860 (*) | 3884 (*) | 3992 (A dievčence:) | 4143 | 4286 (*) | 4351 (Dnes) | 4467 | 4569 | 4620 | 4703 | 4827 (To ošmálil si s kravou niekoho) | 4923 (U pani Tildy, ktorá sedela) | 5022 (Ráno do chrámu) | 5124 (Len vzchopiť sa jej, hýbať, domáhať...) | 5224 (A miliónom matkou bude vlasť,) | 5341 | 5419 (*) | 5524 (Ľaď, tutaj! (Z brány vyšiel Tamáši. )) | 5611 (*) | 5723 (Tie polia - ako štice zježili!) | 5818 (Včera, toť,) | 5923 (Ulapil neduh: podludníka jak) | 6034 (Gábor, povedľa) | 6103 | 6203 (A po zápeve kňaza tklivom, po) | 6365 (A koniec. Sprievod hnul sa... Skríkla mať) | 6392 (*) | 6491 (*) | 6610 
Hájnikova žena/002 - I.txt | 104 | 222 | 342 (Za plôtkom horská riava hučí,) | 418
Hájnikova žena/003 - II.txt | 148 | 205 | 312 (Praškoda každé vlákno práv!) | 434 (Tu videl seba votrelca,) | 529 | 634 
Hájnikova žena/004 - III.txt | 117 | 203 | 349 | 411 | 518
Hájnikova žena/005 - IV.txt | 105 | 180
Hájnikova žena/006 - V.txt | 73 | 213 | 309 | 410
Hájnikova žena/008 - VII.txt | 119 (A slovo moci odzunelo,) | 219 | 339 | 434 | 601 | 709 (V úrade lesnom pisár híka:) | 782 | 885 | 987 | 1099 | 1159 | 1285 (To duši jej sa zjavne prieči;) | 1404 (Lež, drahá, kde znak na zmierenie?) | 1545
Hájnikova žena/009 - VIII.txt | 128
Hájnikova žena/010 - Maliniarky.txt | 59 (*) | 247 (*) | 359 | 456 | 541 | 650
Hájnikova žena/011 - IX.txt | 128 (*) | 265 | 385 | 451 | 555 | 655 (S tým na poľovné prešli kúsky) | 778 | 821 | 947 | 1033 | 1112
Hájnikova žena/012 - X.txt | 80 | 170 | 216 | 328
Hájnikova žena/013 - XI.txt | 166 | 247 | 328
Hájnikova žena/015 - XIII.txt | 83 | 184
Hájnikova žena/017 - XV.txt | 55 
Kain/001 - Kain.txt | 93 (A keď v duši znova) | 215 | 333 | 430 | 511 (*) | 596 | 690 (Potok zahučal) | 780 | 898 (Nasluchovala) |  999 | 1107 | 1257 | 1364 | 1459
Kratšia epika historická a spoločenská/001 - Pribina.txt | 120
Kratšia epika historická a spoločenská/002 - Rastislav.txt | 83
Kratšia epika historická a spoločenská/003 - Ľútosť Svätopluka.txt | 56 | 195 | 309 (- - - - - - -) | 389 (Tak či tak: mzda krvi nevinnej, tá,) | 470 | 605
Kratšia epika historická a spoločenská/004 - Bratranci.txt | 93
Kratšia epika historická a spoločenská/005 - Žofia Bosňáková.txt | 39 | 185 | 275 | 352 (*) | 452 | 553 (*)
Kratšia epika historická a spoločenská/006 - Alžbeta Thurzová.txt | 94 (2) | 156 | 271 | 396 (Stúpa, po štebľoch jak, ešte) | 497 (Líške tiež slasť vonia v hrozne a priam za tým páchol kyseľ.) | 548 (Vbehli deti - hádam z katechizmu;) | 640 (Utiahla sa v svoj kút, ani obeť) | 722 | 821 | 885 | 925 (Čo? dokiaľ do zrkadla) | 1039 (3) | 1126 (4) | 1238 | 1352 (Za okamihom okamih,) | 1418 (Nuž, úzkostlivý tajomník) | 1517 (5) | 1646 (6) | 1758 | 1871
Kratšia epika historická a spoločenská/007 - Imro Tekeľ.txt | 98 | 226 | 321 (2) | 429 | 464 (3) | 567 | 662 ("Synku, v sane)
Kratšia epika historická a spoločenská/008 - Pani z Mahoču.txt | 75
Kratšia epika historická a spoločenská/009 - Jánošíkova stupaj.txt | 53 | 172 | 275 (Rajnoha: "Len či dosť pekne) | 383 | 528
Kratšia epika historická a spoločenská/010 - Pomsta mŕtvych.txt | 78
Kratšia epika historická a spoločenská/011 - Polyxena Párnická.txt | 123
Kratšia epika historická a spoločenská/012 - Pán Boldko.txt | 121 | 180 | 343 | 477 | 554 | 665 | 775
Kratšia epika historická a spoločenská/013 - Krivoprísažník.txt | 105
Kratšia epika historická a spoločenská/014 - Jedlica.txt | 82
Kratšia epika historická a spoločenská/015 - Susedia.txt | 99
Kratšia epika historická a spoločenská/016 - Páni majstri.txt | 89
Kratšia epika historická a spoločenská/018 - Dva vŕšky.txt | 63
Kratšia epika historická a spoločenská/020 - Proťajšky.txt | 88 (*)
Kratšia epika historická a spoločenská/022 - Dve rieky.txt | 87
Kratšia epika zo života dedinského ľudu/002 - Anča.txt | 87 (*) | 172
Kratšia epika zo života dedinského ľudu/003 - Veštba kukučky.txt | 86
Kratšia epika zo života dedinského ľudu/006 - Zuzanka Hraškovie.txt | 59
Kratšia epika zo života dedinského ľudu/007 - Margita.txt | 81 | 161
Kratšia epika zo života dedinského ľudu/008 - Studnica.txt | 127 | 224 (Vo slobodnom vydýchla si;) | 341 | 470
Kratšia epika zo života dedinského ľudu/009 - Smelá Katka.txt | 79 | 187 | 276 | 362 | 482 (- - - - - - - -) | 563 | 656 | 817 (- - - - - - -) | 939 (Objedza na všetky chvály,) | 1074
Kratšia epika zo života dedinského ľudu/010 - Topeľci.txt | 121 (Tanec, úchvat. "Vrátiš mi ju?...) | 228 (Taká vrava, také umy -) | 329 ("Viacej kto?" "Kto? - ty var' menej?") | 359 (*) | 475 | 575 (Mesiačik im ligotavý) | 663 (*) | 773 ("... Nekrč sa, je na tebe rad,) | 829 | 971
Kratšia epika zo života dedinského ľudu/011 - Na Luciu.txt | 64 (PRVÁ ŽENA (predbehnúc iné):) | 129 (VIACERÉ (razom):) | 199 (KTORÁSI (so smiechom):) | 295 (STARENA:) | 425 (ŠUMIHORKA (dojdúc práve s bremenom):) | 555 (NOTÁRKA (dociepkajúc s nákladom):) | 658 (CHLAP (prejdúc povedľa, ohlási sa):) | 800 (DEDINSKÝ VERŠOVNÍK (vykračujúc si, rečňuje):) | 899 ((Pastier dochodí, stenajúc pod ťarchou. )) | 989 (VERŠOVNÍK:) | 1085 (PAHOLOK:) | 1213 (CHLAPEC (vybehnúc z postrannej chalupy, skričí):) | 1310 (NEZNÁMY (hneď fufnave, hneď škrekľave):) | 1346 (PRVÝ HLAS:) | 1504 (JEDNA Z POSTÁV:) | 1597 (INÝ HLAS:) | 1670 (OHLAS:) | 1727 (- - -) | 1821 (VŠETCI:) | 1914 (MORUŠ (predhupne):) | 2026 (DRUŽINA (chórom):) | 2120 (ŠKRIATOK:) | 2205 (ČEĽAĎ (striedave):) | 2308 (VELES:) | 2407 (PIKULÍK:) | 2499 (ZMOK (zjašene):) | 2608 (RARÁŠEK:) | 2687 (PONIEKTORÍ Z LEŠOV A VLKOLAKOV (zvýsknuc a pokazujúc v úboč):) | 2769 (ŠKRIATKY (túliac sa k Velesovi):) | 2864 (Tiež kráčam domov - ale zrazu moc) | 2950 (DIEVČINA (precitne z mdloby a zrazu vztýči sa vo vytržení):)
Kratšia epika zo života dedinského ľudu/012 - Mladá vdova.txt | 185 (*) | 271 (Čarodej ten býval - var' v zámku, detičky? nie:) | 367 (Vzal palicu. "Zámok má stáť hen na čistine!") | 455 ("A čis' nečul, Klingaš že zhodil z pántu zvonec?...) | 556 (Čeľaď vyslúchala, čo vykladal tak nad ním.) | 658 (Janko zmrzol na ľad. Síc' tušil pôvod klamu,) | 742 (Koľko spriadli kýt už? spriasť majú hrubo, tenko) | 842 (Anička vše, žmurk!... si cnie; ústka nakrivelé) | 918 (*) | 1029 (Obrtľom sa otočila,) | 1139 (Vatru nato ošetril; po iskerných strelách) | 1226 (Po povale sstrečkoval plameň prez brvienka,) | 1304
Kratšia epika zo života dedinského ľudu/013 - Matúš Stolár.txt | 92 | 166
Kratšia epika zo života dedinského ľudu/014 - Zuzka Majerovie.txt | 63
Kratšia epika zo života dedinského ľudu/015 - Deľba dedičstva.txt | 99
Kratšia epika zo života dedinského ľudu/016 - Jano Garazda.txt | 84 | 162 | 210
Kratšia epika zo života dedinského ľudu/017 - Šumihorka.txt | 88
Kratšia epika zo života dedinského ľudu/018 - Vrtohlávka.txt | 130 ("Viem! - som kosil ďatelinu.) | 245 (*) | 360
Kratšia epika zo života dedinského ľudu/020 - Potecha.txt | 127 (Chcela vstať, však pridržal ju.) 
Kratšia epika zo života dedinského ľudu/021 - Na výhone.txt | 70 (II.)
Kratšia epika zo života dedinského ľudu/022 - Miško Káčer.txt | 98 | 198 | 298
Kratšia epika zo života dedinského ľudu/023 - Mlatba.txt | 101
Kratšia epika zo života dedinského ľudu/024 - Oráč a kosec.txt | 139 (*) | 222
Kratšia epika zo života dedinského ľudu/025 - Na salaši.txt | 122 (VALASI:) | 264 (BAČA:) | 399 (BAČA:) | 574 (BAČA:) | 685 | 850 (BAČA:) | 946 (BAČA:) | 1051 (VALASI A HONELNÍK:) | 1208 (BAČA:) | 1270 | 1460 (BAČA:) | 1605 (VALASI(ako sbor):) | 1747 (BAČA:) | 1933 | 2128 (BAČA:) | 2222 (BAČA:) | 2285
Kratšia epika zo života dedinského ľudu/026 - Dve návštevy.txt | 129 (Komu postúpim ja miesto,) | 281 (Rýchle prešiel na hovoru) | 333 | 454 ("Ja mám do učenia vôľu!") | 579 (Nechcela som nastoliť jej:) | 654 ("Tedy u farára, nášho) | 726 (II.) | 809 | 929 (Pred Blažkovci) | 1038 (Chlapec poskubol ju. "Gabko, pst," mu) | 1114 (No kde v tomto pohyb totu, pokrok...?) | 1231 (Ale tak je, zákon: jalové či)
Krvavé sonety/001 - Krvavé sonety.txt | 135 (*) | 230 (*) | 324 (*) | 419 (*) | 514 (*)
Letorosty I/006 - Ach, nevoľa!.txt | 53 | 101 | 132
Letorosty II/008 - 26. novembra 1886.txt | 73 | 147 | 206 | 286 | 334 | 371
Letorosty II/009 - Čierny rok.txt | 97 (1884) | 193 | 298
Letorosty III/004 - Matka zem.txt | 65 | 186 (Voj zbrnavelý) | 327
Letorosty III/012 - Ó, prečo som nie víchrom!?.txt | 81 
Letorosty III/013 - Elégie pôstne.txt | 100
Letorosty III/025 - K vám, urodzeným, veľkomožným.txt | 33 | 195
Letorosty III/026 - Ruch v poli.txt | 93 (Ha! kosí cveng a záblesk ligotný,)
Na obnôcke/001 - Na obnôcke.txt | 107 | 193 (*) | 261 | 341 | 380 | 440 | 467 (*) | 510 | 580 | 661 | 709 | 798 (*) | 876 | 992 (*) | 1060 (*)
Poludienok/001 - Poludienok.txt | 78 (On jedol -) | 180 | 269 (Zbadala či nie, že už posmieva) | 347 | 426
Prechádzky jarom/009 - Breh, vŕšok, bralo, hoľa, Tatier štít.txt | (101) Tomu zjaveniu
Prechádzky letom/001 - Nie: teba, slnko slávne, neovládze.txt | 59 (Ba tmavá noc,) | 111 (Čo ti v očiach zem,) | 220 (Dnes - zvláštno to!) | 297 (Som herold - slnca -)
Prechádzky letom/008 - Za jara zavše vídať v dúbrave.txt | 106
Prechádzky letom/009 - Cveng kosí... až vše v slnku zblýska sa!.txt | 76 | 124 (*)
Prechádzky letom/010 - Zvážajú z poľa... radosť, veselie.txt | 131 (Ó, ten voz pozemský) | 225 (Ja čo? Ach -)
Prvý záprah/001 - Prvý záprah.txt | 103 | 228 | 313 | 393
Ráchel/001 - I.txt | 129 | 235
Ráchel/002 - II.txt | 93 | 192 | 277
Ráchel/003 - III.txt | 111 | 210
Ráchel/004 - IV.txt | 39
Ráchel/005 - V.txt | 66
Stesky 1/005 - Ó, po tak dlhej trápnej suchote.txt | 66
Stesky 1/006 - Nedávno, jak tak v izbe sedím si.txt | 103 (Až zarazený, vetím konečne:) | 251 (Stred záhrady tej, plochou nesmiernej)
Stesky 1/012 - Čo tak tie piesne naše nábožné.txt | 80 (A oba)
Stesky 1/013 - Už za detstva, snáď čo som prvý raz.txt | 87
Stesky 1/014 - Po poliach, stráňach chodí Jaro.txt | 110 (*) | 221 (*) | 278 (*)
Stesky 1/016 - Ó, smutno duši.txt | 82
Stesky 1/023 - Som na vrchole veku ľudského.txt | (105) K tomu pribavil | 223 (A pavlač tiež tam, žuly podolok) | 302 (Ach, dobré srdcia, lásky úrodou)
Stesky 2/001 - Ja s plnou dušou vrátil som sa.txt | 103 (Kam stratil si sa duchom? koho očakávaš,) | 154  (Bláznovstvo!...) | 228 (1900)
Stesky 2/013 - Čítal iste ako malý žiačik.txt | 55 (*) | 77 (*)
Stesky 2/015 - Nedávno starec chodil u mňa.txt | 121
Stesky 2/018 - Slnce, životodarca!.txt | 111
Stesky 2/019 - Že zvuky mojej citnej lýry.txt | 93
Stesky 2/020 - V tom, čo som bol zabral po rokoch.txt |  188
Stesky 2/024 - Zaduli vetry.txt | 74
Stesky 3/004 - Jak príroda len začne klíčiť trávky.txt | 66
Stesky 3/009 - Čo pechoríte sa?.txt | 63
Stesky 3/011 - Som decko zas....txt | 169
Stesky 4/002 - Ó, práci všetka česť, česť práci všetka!.txt | 59
Stesky 4/003 - Smrť v susedstve!.txt | 110
Stesky 4/011 - Tak sám a sám!....txt | 78
Stesky 4/015 - Zájď, slnko, zájď už!.txt | 108 | 142 | 257
Stesky 4/016 - Koľkorázkoľvek už čo zrelý muž.txt | 102 | 228 (Onehdy)
Stesky 4/017 - Na bujnej si lúke ležím horeznačky.txt | 93
Stesky 4/018 - Návšteva.txt | 114 | 235 | 312 | 411 | 514 | 616
Stesky 4/019 - Kukučínovi.txt | 159 | 240
Stesky 4/020 - Za oných časov snivej mladosti.txt | 156 | 218 (*) | 331 (*)
Stesky 4/021 - Slovenský Prometej.txt | 66 | 204 | 364 (Tam, áno! tam) | 431 (Toť, onen byt a syt!) | 503 | 548 | 580
Stesky 4/022 - U nás toľko rezkej sily.txt | 94 | 228 | 370 (*) | 456 (*) | 506 (*) | 552 (*)
Stesky 4/024 - Ďakujte na kolenách bohu!.txt | 131
Stesky 4/028 - Epilóg.txt | 100
V pamäť/001 - Roľník.txt | 97 | 143 | 244
V pamäť/002 - Priadka.txt | 93 | 198 (*) 
V pamäť/003 - Nový život.txt | 82
V žatvu/001 - V žatvu.txt | 77 (Ináč nepovedlo) | 126 (Inu,) | 160 (Samo však dosť staré je, by ľúbilo hračky...) | 211 (Znalo tedy slniečko i dnes, čo je treba.) | 238 | 292 | 331 | 415 | 519 | 549 | 647 | 689 | 745 | 802 | 890 (No všetko to razom sotrel, smazal) | 933 | 975 | 1021 | 1086 | 1118 | 1163 | 1267 | 1386 (Ostal som sám -)
Večera/001 - Večera.txt | 73 | 182 (Hupkom do kuchyne skokla.) | 246 | 296 | 380 | 417 | 482 | 538 | 639 | 762 (Jajatka vošiel - jemu riekla: "To vy!) | 845
Z básní, venovaných A. Medzihradskému/016 - Jarný ples.txt | 86 (*)
Z básní, venovaných A. Medzihradskému/023 - Stará lipa.txt | 110 (*)
Z básní, venovaných A. Medzihradskému/025 - Z našich dva zvyky.txt | 126 (*)
Žalmy a hymny/001 - Žalm na tisícročnú pamiatku vierozvestcov sv. Cyrila a Metodeja.txt | 123
Žalmy a hymny/002 - Žalm ku závierke roku.txt | 154
Žalmy a hymny/003 - Žalm žaloby.txt | 69
Žalmy a hymny/004 - De Profundis.txt | 43 | 81
Žalmy a hymny/008 - Hviezdnaté nebo.txt | 78
Žalmy a hymny/010 - Blízko si, Pane!.txt | 73 | 126
Žalmy a hymny/011 - Žalm života.txt | 105
"""

FULL_LENGTH_DATA_DIR = "data/full_length"
CHUNKED_DATA_DIR = "data/chunked"


def main():
    """Main function to execute the scrip."""
    if not os.path.exists(FULL_LENGTH_DATA_DIR):
        print(
            "The full-length data directory does not exist. "
            "Please run the `full_length_stas.py` script to download and extract the data."
        )
        return

    print("Creating chunked poems...")
    poem_paths = get_poem_paths()

    splits = parse_splitting_instructions()

    # Populate the splits dictionary with poems that are "not long"
    for poem_path in poem_paths:
        print(f"Poem path {poem_path}", end=" ")
        if poem_path not in splits:
            print("IS NOT in splitting instructions")
            splits[poem_path] = [[0, None]]
        else:
            print("IS in splitting instructions")

    print("Cleaning chunks...")
    cleaned_splits = {}
    for poem_path, chunks in splits.items():
        cleaned_chunks = clean_chunks(poem_path, chunks)
        cleaned_splits[poem_path] = cleaned_chunks

    print("Saving chunked poems...")
    save_chunked(cleaned_splits)


def get_poem_paths():
    """
    Get the names of all available poems (in the full-length data directory).

    Returns:
        list: List of poem names.
    """
    poem_paths = []
    for root, _, poem_filenames in os.walk(FULL_LENGTH_DATA_DIR):
        book = os.path.basename(root)
        for poem_filename in poem_filenames:
            poem_paths.append(os.path.join(book, poem_filename))

    return sorted(poem_paths)


def parse_splitting_instructions():
    """
    Parse the splitting instructions to determine the chunks for each poem.

    Returns:
        dict: Dictionary with poem names as keys and a list of chunks as values.
    """
    result = {}
    lines = SPLITTING_INSTRUCTIONS.strip().split("\n")

    for line in lines:
        segments = line.split("|")
        poem_path = segments[0].strip()
        split_points = segments[1:]

        chunks = []
        current_start = 0

        for point in split_points:
            match = re.search(r"\s*(\d+)\s*(?:\((.*?)\))?", point)
            if match:
                line_number = int(match.group(1)) - 1  # Convert to 0-based index
                expression = match.group(2).strip() if match.group(2) else ""

                if re.fullmatch(r"\d{4}", expression):
                    chunks.append(
                        [current_start, line_number]
                    )  # The expression is a year when the poem was written - it is only at the end of a poem
                    current_start = line_number + 1
                else:
                    chunks.append([current_start, line_number - 1])
                    current_start = line_number

        chunks.append(
            [current_start, None]
        )  # The last chunk ends at the last line of the poem
        result[poem_path] = chunks

    return result


def clean_chunks(poem_path, chunks):
    """
    Clean the chunks by removing the leading and trailing empty lines.

    Args:
        poem_name (str): Name of the poem.
        chunks (list): List of chunks ranges.

    Returns:
        list: List of cleaned chunk ranges.
    """
    poem_lines = open(os.path.join(FULL_LENGTH_DATA_DIR, poem_path), "r").readlines()
    cleaned_chunks = []
    for start, end in chunks:
        if end is None:
            end = len(poem_lines) - 1

        for new_start in range(start, end + 1):
            if poem_lines[new_start].strip():
                break

        for new_end in range(end, start - 1, -1):
            if poem_lines[new_end].strip():
                break

        cleaned_chunks.append([new_start, new_end])

    return cleaned_chunks


def save_chunked(splits):
    """
    Save the chunked poems to the chunked data directory.

    Args:
        splits (dict): Dictionary with poem names as keys and a list of chunk ranges as values.
    """
    if os.path.exists(CHUNKED_DATA_DIR):
        shutil.rmtree(CHUNKED_DATA_DIR)

    os.makedirs(CHUNKED_DATA_DIR)

    for poem_path, chunks in splits.items():
        book_name, poem_filename = poem_path.split("/")
        poem_name = poem_filename.split(".")[0]
        print(f"Book and poem name: {book_name} / {poem_name}")
        os.makedirs(os.path.join(CHUNKED_DATA_DIR, book_name), exist_ok=True)
        poem_lines = open(
            os.path.join(FULL_LENGTH_DATA_DIR, book_name, poem_filename), "r"
        ).readlines()
        for i, (start, end) in enumerate(chunks):
            chunk_filename = f"{poem_name}_{i:02d}.txt"
            print(f" - creating chunk {i} filename {chunk_filename}")
            with open(
                os.path.join(CHUNKED_DATA_DIR, book_name, chunk_filename), "w"
            ) as f:
                for line in poem_lines[start : end + 1]:
                    f.write(line)


if __name__ == "__main__":
    main()
